openapi: 3.0.3
info:
  title: E-Commerce Platform API
  description: |
    E-Commerce Microservices Platform API documentation.

    ## Authentication
    Most endpoints require JWT authentication. Include the token in the Authorization header:
    ```
    Authorization: Bearer <token>
    ```

    ## Services
    - **Customer Service**: User registration, authentication, membership
    - **Product Service**: Product catalog, search, categories
    - **Order Service**: Shopping cart, order management
    - **Payment Service**: Payment processing
    - **Logistics Service**: Shipment tracking
    - **Sales Service**: Promotions and coupons
    - **Admin Portal**: Back-office management
  version: 1.0.0
  contact:
    name: E-Commerce Team
    email: support@ecommerce.com

servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://api.ecommerce.com
    description: Production

tags:
  - name: Authentication
    description: Customer authentication endpoints
  - name: Customers
    description: Customer profile and membership
  - name: Products
    description: Product catalog and search
  - name: Cart
    description: Shopping cart management
  - name: Orders
    description: Order management
  - name: Payments
    description: Payment processing
  - name: Shipments
    description: Shipment tracking
  - name: Promotions
    description: Promotions and coupons
  - name: Admin
    description: Admin portal endpoints

paths:
  # Authentication
  /api/auth/login:
    post:
      tags: [Authentication]
      summary: Customer login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials

  /api/customers/register:
    post:
      tags: [Customers]
      summary: Register new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Customer registered
        '400':
          description: Validation error
        '409':
          description: Email already exists

  # Customer
  /api/customers/me:
    get:
      tags: [Customers]
      summary: Get current customer profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Customer profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProfile'

  /api/customers/me/membership:
    get:
      tags: [Customers]
      summary: Get membership information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Membership details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembershipResponse'

  # Products
  /api/v1/products:
    get:
      tags: [Products]
      summary: List products
      parameters:
        - name: category
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductSummary'

  /api/v1/products/{id}:
    get:
      tags: [Products]
      summary: Get product details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
        '404':
          description: Product not found

  /api/v1/products/search:
    get:
      tags: [Products]
      summary: Search products
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductSummary'

  # Cart
  /api/v1/cart:
    get:
      tags: [Cart]
      summary: Get shopping cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cart contents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /api/v1/cart/items:
    post:
      tags: [Cart]
      summary: Add item to cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddToCartRequest'
      responses:
        '200':
          description: Item added

  /api/v1/cart/items/{itemId}:
    put:
      tags: [Cart]
      summary: Update cart item quantity
      security:
        - bearerAuth: []
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCartItemRequest'
      responses:
        '200':
          description: Item updated

    delete:
      tags: [Cart]
      summary: Remove item from cart
      security:
        - bearerAuth: []
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Item removed

  # Orders
  /api/v1/orders:
    get:
      tags: [Orders]
      summary: Get order history
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Order list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderSummary'

    post:
      tags: [Orders]
      summary: Create order from cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'

  # Shipments
  /api/v1/shipments/{orderId}/tracking:
    get:
      tags: [Shipments]
      summary: Get shipment tracking
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Tracking information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackingResponse'

  # Promotions
  /api/v1/promotions:
    get:
      tags: [Promotions]
      summary: Get active promotions
      responses:
        '200':
          description: Promotion list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Promotion'

  /api/v1/coupons/validate:
    post:
      tags: [Promotions]
      summary: Validate coupon
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CouponValidateRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponValidationResponse'

  # Admin
  /api/admin/auth/login:
    post:
      tags: [Admin]
      summary: Admin login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminAuthResponse'

  /api/admin/products:
    get:
      tags: [Admin]
      summary: List products (admin)
      security:
        - adminAuth: []
      responses:
        '200':
          description: Product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminProductSummary'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    adminAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8

    AuthResponse:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        email:
          type: string
        token:
          type: string
        expiresIn:
          type: integer

    RegisterRequest:
      type: object
      required: [email, password, firstName, lastName]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string

    CustomerProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        memberLevel:
          type: string
          enum: [NORMAL, SILVER, GOLD, PLATINUM]

    MembershipResponse:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        memberLevel:
          type: string
        totalSpending:
          type: number
        spendingToNextLevel:
          type: number
        discountPercentage:
          type: integer
        benefitDescription:
          type: string

    ProductSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
        imageUrl:
          type: string

    ProductDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        category:
          type: string
        images:
          type: array
          items:
            type: string

    Cart:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        totalAmount:
          type: number

    CartItem:
      type: object
      properties:
        itemId:
          type: string
          format: uuid
        productId:
          type: string
          format: uuid
        productName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number

    AddToCartRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: string
          format: uuid
        quantity:
          type: integer
          minimum: 1

    UpdateCartItemRequest:
      type: object
      required: [quantity]
      properties:
        quantity:
          type: integer
          minimum: 1

    CreateOrderRequest:
      type: object
      required: [shippingAddressId, paymentMethod]
      properties:
        shippingAddressId:
          type: string
          format: uuid
        paymentMethod:
          type: string
          enum: [CREDIT_CARD, BANK_TRANSFER, COD]
        couponCode:
          type: string

    OrderSummary:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
        status:
          type: string
        totalAmount:
          type: number
        createdAt:
          type: string
          format: date-time

    OrderResponse:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
        status:
          type: string
        paymentUrl:
          type: string

    TrackingResponse:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
        trackingNumber:
          type: string
        carrier:
          type: string
        status:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/TrackingEvent'

    TrackingEvent:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: string
        location:
          type: string
        description:
          type: string

    Promotion:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        discountType:
          type: string
        discountValue:
          type: number
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    CouponValidateRequest:
      type: object
      required: [couponCode, orderTotal]
      properties:
        couponCode:
          type: string
        orderTotal:
          type: number

    CouponValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
        couponCode:
          type: string
        discountAmount:
          type: number
        errorMessage:
          type: string

    AdminLoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    AdminAuthResponse:
      type: object
      properties:
        adminId:
          type: string
          format: uuid
        email:
          type: string
        name:
          type: string
        role:
          type: string
        permissions:
          type: array
          items:
            type: string
        token:
          type: string

    AdminProductSummary:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        sku:
          type: string
        name:
          type: string
        price:
          type: number
        stock:
          type: integer
        active:
          type: boolean
